// Bay Area Golf Courses - Full dataset from src/db/courses.js
// This is the source of truth for course data in the Next.js app

export interface Course {
  name: string
  slug: string
  city: string
  region: string
  holes: number
  par: number | null
  yardage: number | null
  latitude: number | null
  longitude: number | null
  phone_number: string | null
  golfnow_id: string | null
  booking_url: string
  booking_system: string
  description?: string
}

// Generate URL-friendly slug from course name
function generateSlug(name: string): string {
  return name
    .toLowerCase()
    .replace(/['']/g, "")
    .replace(/[^a-z0-9\s-]/g, "")
    .replace(/\s+/g, "-")
    .replace(/-+/g, "-")
    .replace(/^-|-$/g, "")
}

const rawCourses = [
  // San Francisco
  {
    name: "TPC Harding Park",
    city: "San Francisco",
    region: "San Francisco",
    holes: 18,
    par: 72,
    yardage: 7169,
    latitude: 37.724,
    longitude: -122.493,
    phone_number: "(415) 664-4690",
    golfnow_id: "8276",
    booking_url: "https://www.golfnow.com/tee-times/facility/8276-tpc-harding-park-golf-club/search",
    booking_system: "golfnow",
    description:
      "Championship course that has hosted PGA Tour events including the 2020 PGA Championship won by Collin Morikawa.",
  },
  {
    name: "Lincoln Park Golf Course",
    city: "San Francisco",
    region: "San Francisco",
    holes: 18,
    par: 68,
    yardage: 5181,
    latitude: 37.7833,
    longitude: -122.4956,
    phone_number: "(415) 221-9911",
    golfnow_id: "556",
    booking_url: "https://www.golfnow.com/tee-times/facility/556-lincoln-park-golf-course/search",
    booking_system: "golfnow",
    description: "Historic municipal course with stunning views of the Golden Gate Bridge and the Marin Headlands.",
  },
  {
    name: "Sharp Park Golf Course",
    city: "Pacifica",
    region: "San Francisco",
    holes: 18,
    par: 72,
    yardage: 6274,
    latitude: 37.6239,
    longitude: -122.4894,
    phone_number: "(650) 359-3380",
    golfnow_id: "619",
    booking_url: "https://www.golfnow.com/tee-times/facility/619-sharp-park-golf-course/search",
    booking_system: "golfnow",
    description: "Alister MacKenzie-designed coastal links course along the Pacific Ocean.",
  },
  {
    name: "Presidio Golf Course",
    city: "San Francisco",
    region: "San Francisco",
    holes: 18,
    par: 72,
    yardage: 6477,
    latitude: 37.7905,
    longitude: -122.4657,
    phone_number: "(415) 561-4661",
    golfnow_id: null,
    booking_url: "https://www.presidiogolf.com",
    booking_system: "cpsgolf",
    description: "Historic course in the Presidio with towering eucalyptus and cypress trees.",
  },
  {
    name: "Golden Gate Park Golf Course",
    city: "San Francisco",
    region: "San Francisco",
    holes: 9,
    par: 27,
    yardage: 1357,
    latitude: 37.7694,
    longitude: -122.4862,
    phone_number: "(415) 751-8987",
    golfnow_id: null,
    booking_url: "https://sfrecpark.org/",
    booking_system: "other",
    description: "Compact 9-hole course in beautiful Golden Gate Park, perfect for beginners.",
  },
  {
    name: "Fleming Golf Course",
    city: "San Francisco",
    region: "San Francisco",
    holes: 9,
    par: 27,
    yardage: 1200,
    latitude: 37.7208,
    longitude: -122.4978,
    phone_number: "(415) 585-0546",
    golfnow_id: null,
    booking_url: "https://sfrecpark.org/",
    booking_system: "other",
    description: "Beginner-friendly 9-hole course in the Sunset District.",
  },
  {
    name: "Gleneagles Golf Course",
    city: "San Francisco",
    region: "San Francisco",
    holes: 9,
    par: 36,
    yardage: 2876,
    latitude: 37.7147,
    longitude: -122.4232,
    phone_number: "(415) 587-2425",
    golfnow_id: null,
    booking_url: "https://www.gleneaglesgc.com/",
    booking_system: "other",
    description: "Scenic 9-hole course in McLaren Park with challenging terrain.",
  },
  {
    name: "Poplar Creek Golf Course",
    city: "San Mateo",
    region: "San Francisco",
    holes: 18,
    par: 60,
    yardage: 3200,
    latitude: 37.5847,
    longitude: -122.3532,
    phone_number: "(650) 522-4653",
    golfnow_id: "594",
    booking_url: "https://www.golfnow.com/tee-times/facility/594-poplar-creek-golf-course/search",
    booking_system: "golfnow",
    description: "Executive course in San Mateo, great for a quick round.",
  },

  // South Bay - Santa Clara County
  {
    name: "San Jose Municipal Golf Course",
    city: "San Jose",
    region: "South Bay",
    holes: 18,
    par: 72,
    yardage: 6700,
    latitude: 37.3494,
    longitude: -121.91,
    phone_number: "(408) 441-4653",
    golfnow_id: null,
    booking_url: "https://sanjose.totaleintegrated.net/web/tee-times",
    booking_system: "totaleintegrated",
    description: "Well-maintained municipal course in San Jose.",
  },
  {
    name: "Cinnabar Hills Golf Club",
    city: "San Jose",
    region: "South Bay",
    holes: 27,
    par: 72,
    yardage: 6853,
    latitude: 37.2419,
    longitude: -121.775,
    phone_number: "(408) 323-5200",
    golfnow_id: "465",
    booking_url: "https://www.golfnow.com/tee-times/facility/465-cinnabar-hills-golf-club/search",
    booking_system: "golfnow",
    description: "Award-winning 27-hole facility in the foothills with three distinct nines.",
  },
  {
    name: "Los Lagos Golf Course",
    city: "San Jose",
    region: "South Bay",
    holes: 18,
    par: 60,
    yardage: 3700,
    latitude: 37.2878,
    longitude: -121.8208,
    phone_number: "(408) 361-0250",
    golfnow_id: "561",
    booking_url: "https://www.golfnow.com/tee-times/facility/561-los-lagos-golf-course/search",
    booking_system: "golfnow",
    description: "Executive course perfect for working on your short game.",
  },
  {
    name: "Santa Teresa Golf Club",
    city: "San Jose",
    region: "South Bay",
    holes: 18,
    par: 71,
    yardage: 6738,
    latitude: 37.2295,
    longitude: -121.796,
    phone_number: "(408) 225-2650",
    golfnow_id: null,
    booking_url: "https://www.chronogolf.com/club/santa-teresa-golf-club",
    booking_system: "chronogolf",
    description: "Challenging hillside course with panoramic valley views.",
  },
  {
    name: "Boulder Ridge Golf Club",
    city: "San Jose",
    region: "South Bay",
    holes: 18,
    par: 72,
    yardage: 6806,
    latitude: 37.2208,
    longitude: -121.753,
    phone_number: "(408) 323-9900",
    golfnow_id: "8267",
    booking_url: "https://www.golfnow.com/tee-times/facility/8267-boulder-ridge-golf-club/search",
    booking_system: "golfnow",
    description: "Robert Muir Graves design winding through the hills.",
  },
  {
    name: "Pruneridge Golf Club",
    city: "Santa Clara",
    region: "South Bay",
    holes: 9,
    par: 30,
    yardage: 1768,
    latitude: 37.3622,
    longitude: -121.9886,
    phone_number: "(408) 248-4424",
    golfnow_id: "596",
    booking_url: "https://www.golfnow.com/tee-times/facility/596-pruneridge-golf-club/search",
    booking_system: "golfnow",
    description: "Convenient 9-hole course in the heart of Silicon Valley.",
  },
  {
    name: "Deep Cliff Golf Course",
    city: "Cupertino",
    region: "South Bay",
    holes: 18,
    par: 60,
    yardage: 3200,
    latitude: 37.3206,
    longitude: -122.0492,
    phone_number: "(408) 253-5357",
    golfnow_id: "474",
    booking_url: "https://www.golfnow.com/tee-times/facility/474-deep-cliff-golf-course/search",
    booking_system: "golfnow",
    description: "Executive course in Cupertino with well-maintained greens.",
  },
  {
    name: "Sunnyvale Golf Course",
    city: "Sunnyvale",
    region: "South Bay",
    holes: 18,
    par: 70,
    yardage: 5858,
    latitude: 37.39,
    longitude: -122.012,
    phone_number: "(408) 738-3666",
    golfnow_id: "639",
    booking_url: "https://www.golfnow.com/tee-times/facility/639-sunnyvale-golf-course/search",
    booking_system: "golfnow",
    description: "Flat, walkable course ideal for all skill levels.",
  },
  {
    name: "Sunken Gardens Golf Course",
    city: "Sunnyvale",
    region: "South Bay",
    holes: 9,
    par: 29,
    yardage: 1495,
    latitude: 37.3778,
    longitude: -122.045,
    phone_number: "(408) 739-6588",
    golfnow_id: "638",
    booking_url: "https://www.golfnow.com/tee-times/facility/638-sunken-gardens-golf-course/search",
    booking_system: "golfnow",
    description: "Compact par-3 course perfect for practice rounds.",
  },
  {
    name: "Spring Valley Golf Course",
    city: "Milpitas",
    region: "South Bay",
    holes: 18,
    par: 70,
    yardage: 5132,
    latitude: 37.444,
    longitude: -121.9108,
    phone_number: "(408) 262-1722",
    golfnow_id: "630",
    booking_url: "https://www.golfnow.com/tee-times/facility/630-spring-valley-golf-course/search",
    booking_system: "golfnow",
    description: "Friendly course with affordable rates in Milpitas.",
  },
  {
    name: "Coyote Creek Golf Club",
    city: "Morgan Hill",
    region: "South Bay",
    holes: 36,
    par: 72,
    yardage: 7011,
    latitude: 37.139,
    longitude: -121.622,
    phone_number: "(408) 463-1400",
    golfnow_id: "469",
    booking_url: "https://www.golfnow.com/tee-times/facility/469-coyote-creek-golf-club/search",
    booking_system: "golfnow",
    description: "36-hole facility with Valley and Tournament courses.",
  },
  {
    name: "Moffett Field Golf Course",
    city: "Mountain View",
    region: "South Bay",
    holes: 18,
    par: 72,
    yardage: 6685,
    latitude: 37.4138,
    longitude: -122.0508,
    phone_number: "(650) 603-8026",
    golfnow_id: "573",
    booking_url: "https://www.golfnow.com/tee-times/facility/573-moffett-field-golf-course/search",
    booking_system: "golfnow",
    description: "Military-style course near NASA Ames Research Center.",
  },
  {
    name: "Blackberry Farm Golf Course",
    city: "Cupertino",
    region: "South Bay",
    holes: 9,
    par: 29,
    yardage: 1240,
    latitude: 37.3155,
    longitude: -122.0645,
    phone_number: "(408) 253-9200",
    golfnow_id: null,
    booking_url: "https://www.cupertino.org/",
    booking_system: "other",
    description: "City-owned 9-hole course in a beautiful park setting.",
  },
  {
    name: "Palo Alto Golf Course",
    city: "Palo Alto",
    region: "South Bay",
    holes: 18,
    par: 72,
    yardage: 6217,
    latitude: 37.4543,
    longitude: -122.1178,
    phone_number: "(650) 856-0881",
    golfnow_id: "586",
    booking_url: "https://www.golfnow.com/tee-times/facility/586-palo-alto-golf-course/search",
    booking_system: "golfnow",
    description: "Municipal course near the Baylands with flat, walkable layout.",
  },
  {
    name: "Baylands Golf Links",
    city: "Palo Alto",
    region: "South Bay",
    holes: 18,
    par: 71,
    yardage: 6680,
    latitude: 37.459,
    longitude: -122.1066,
    phone_number: "(650) 856-0881",
    golfnow_id: null,
    booking_url: "https://baylandsbw.ezlinksgolf.com",
    booking_system: "ezlinks",
    description: "Links-style course with bay views and challenging winds.",
  },
  {
    name: "Stanford Golf Course",
    city: "Stanford",
    region: "South Bay",
    holes: 18,
    par: 71,
    yardage: 6727,
    latitude: 37.4347,
    longitude: -122.1732,
    phone_number: "(650) 323-0944",
    golfnow_id: "631",
    booking_url: "https://www.golfnow.com/tee-times/facility/631-stanford-golf-course/search",
    booking_system: "golfnow",
    description: "Beautiful tree-lined course on the Stanford campus.",
  },

  // Peninsula - Half Moon Bay
  {
    name: "Half Moon Bay - Old Course",
    city: "Half Moon Bay",
    region: "South Bay",
    holes: 18,
    par: 72,
    yardage: 7007,
    latitude: 37.4328,
    longitude: -122.4542,
    phone_number: "(650) 726-1800",
    golfnow_id: null,
    booking_url: "https://www.chronogolf.com/club/half-moon-bay-golf-links",
    booking_system: "chronogolf",
    description: "Classic Arnold Palmer design with ocean views.",
  },
  {
    name: "Half Moon Bay - Ocean Course",
    city: "Half Moon Bay",
    region: "South Bay",
    holes: 18,
    par: 72,
    yardage: 6732,
    latitude: 37.4328,
    longitude: -122.4542,
    phone_number: "(650) 726-1800",
    golfnow_id: null,
    booking_url: "https://www.chronogolf.com/club/half-moon-bay-golf-links",
    booking_system: "chronogolf",
    description: "Stunning oceanfront course along the Pacific cliffs.",
  },
  {
    name: "Pasatiempo Golf Club",
    city: "Santa Cruz",
    region: "South Bay",
    holes: 18,
    par: 70,
    yardage: 6439,
    latitude: 37.005,
    longitude: -122.056,
    phone_number: "(831) 459-9155",
    golfnow_id: "4759",
    booking_url: "https://www.golfnow.com/tee-times/facility/4759-pasatiempo-golf-club/search",
    booking_system: "golfnow",
    description: "Legendary Alister MacKenzie design, ranked among the best in the country.",
  },

  // East Bay - Alameda County
  {
    name: "Corica Park - South Course",
    city: "Alameda",
    region: "East Bay",
    holes: 18,
    par: 71,
    yardage: 6666,
    latitude: 37.7392,
    longitude: -122.2333,
    phone_number: "(510) 747-7800",
    golfnow_id: "8136",
    booking_url: "https://www.golfnow.com/tee-times/facility/8136-corica-park-south-course/search",
    booking_system: "golfnow",
    description: "Recently renovated Rees Jones design with modern facilities.",
  },
  {
    name: "Corica Park - North Course",
    city: "Alameda",
    region: "East Bay",
    holes: 18,
    par: 70,
    yardage: 6056,
    latitude: 37.745,
    longitude: -122.234,
    phone_number: "(510) 747-7800",
    golfnow_id: "514",
    booking_url: "https://www.golfnow.com/tee-times/facility/514-corica-park-north-course/search",
    booking_system: "golfnow",
    description: "Well-maintained course with water features.",
  },
  {
    name: "Corica Park - Mif Albright Par 3",
    city: "Alameda",
    region: "East Bay",
    holes: 9,
    par: 27,
    yardage: 1100,
    latitude: 37.742,
    longitude: -122.235,
    phone_number: "(510) 747-7800",
    golfnow_id: "8713",
    booking_url: "https://www.golfnow.com/tee-times/facility/8713-corica-park-mif-albright-par-3/search",
    booking_system: "golfnow",
    description: "Perfect par-3 course for beginners and short game practice.",
  },
  {
    name: "Metropolitan Golf Links",
    city: "Oakland",
    region: "East Bay",
    holes: 18,
    par: 72,
    yardage: 6801,
    latitude: 37.735,
    longitude: -122.21,
    phone_number: "(510) 569-5555",
    golfnow_id: null,
    booking_url: "https://www.metropolitangolflinks.com",
    booking_system: "phone",
    description: "Links-style course near Oakland Airport with great conditions.",
  },
  {
    name: "Lake Chabot Golf Course",
    city: "Oakland",
    region: "East Bay",
    holes: 27,
    par: 72,
    yardage: 6599,
    latitude: 37.7292,
    longitude: -122.092,
    phone_number: "(510) 351-5812",
    golfnow_id: "549",
    booking_url: "https://www.golfnow.com/tee-times/facility/549-lake-chabot-golf-course/search",
    booking_system: "golfnow",
    description: "27-hole facility in the Oakland hills with scenic views.",
  },
  {
    name: "Tilden Park Golf Course",
    city: "Berkeley",
    region: "East Bay",
    holes: 18,
    par: 70,
    yardage: 6294,
    latitude: 37.8881,
    longitude: -122.2441,
    phone_number: "(510) 848-7373",
    golfnow_id: null,
    booking_url: "https://www.chronogolf.com/club/tilden-park-golf-course-california-berkeley",
    booking_system: "chronogolf",
    description: "Beautiful hillside course in Tilden Regional Park.",
  },
  {
    name: "Redwood Canyon Golf Course",
    city: "Castro Valley",
    region: "East Bay",
    holes: 9,
    par: 34,
    yardage: 2580,
    latitude: 37.7215,
    longitude: -122.068,
    phone_number: "(510) 537-8001",
    golfnow_id: null,
    booking_url: "https://www.chronogolf.com/club/redwood-canyon-public-golf-course",
    booking_system: "chronogolf",
    description: "Challenging 9-hole course among the redwoods.",
  },
  {
    name: "Monarch Bay Golf Club",
    city: "San Leandro",
    region: "East Bay",
    holes: 18,
    par: 71,
    yardage: 5845,
    latitude: 37.694,
    longitude: -122.192,
    phone_number: "(510) 895-2162",
    golfnow_id: "574",
    booking_url: "https://www.golfnow.com/tee-times/facility/574-monarch-bay-golf-club/search",
    booking_system: "golfnow",
    description: "Waterfront course with views of San Francisco Bay.",
  },
  {
    name: "Montclair Golf Course",
    city: "Oakland",
    region: "East Bay",
    holes: 9,
    par: 33,
    yardage: 2370,
    latitude: 37.828,
    longitude: -122.205,
    phone_number: "(510) 482-0422",
    golfnow_id: "575",
    booking_url: "https://www.golfnow.com/tee-times/facility/575-montclair-golf-course/search",
    booking_system: "golfnow",
    description: "Neighborhood 9-hole course in the Oakland hills.",
  },

  // East Bay - Contra Costa County
  {
    name: "Boundary Oak Golf Course",
    city: "Walnut Creek",
    region: "East Bay",
    holes: 18,
    par: 72,
    yardage: 7106,
    latitude: 37.9258,
    longitude: -122.052,
    phone_number: "(925) 934-6211",
    golfnow_id: null,
    booking_url: "https://www.playboundaryoak.com",
    booking_system: "phone",
    description: "Championship course with challenging layout and great conditions.",
  },
  {
    name: "Diablo Hills Golf Course",
    city: "Walnut Creek",
    region: "East Bay",
    holes: 9,
    par: 30,
    yardage: 1810,
    latitude: 37.902,
    longitude: -122.045,
    phone_number: "(925) 939-7372",
    golfnow_id: "478",
    booking_url: "https://www.golfnow.com/tee-times/facility/478-diablo-hills-golf-course/search",
    booking_system: "golfnow",
    description: "Executive 9-hole course with Mount Diablo views.",
  },
  {
    name: "Franklin Canyon Golf Course",
    city: "Hercules",
    region: "East Bay",
    holes: 18,
    par: 72,
    yardage: 6490,
    latitude: 37.993,
    longitude: -122.288,
    phone_number: "(510) 799-6191",
    golfnow_id: "498",
    booking_url: "https://www.golfnow.com/tee-times/facility/498-franklin-canyon-golf-course/search",
    booking_system: "golfnow",
    description: "Scenic course winding through Franklin Canyon.",
  },
  {
    name: "Poppy Ridge Golf Course",
    city: "Livermore",
    region: "East Bay",
    holes: 27,
    par: 72,
    yardage: 7104,
    latitude: 37.758,
    longitude: -121.772,
    phone_number: "(925) 447-6779",
    golfnow_id: null,
    booking_url: "https://poppyridgegolf.com",
    booking_system: "phone",
    description: "27-hole Rees Jones design in Livermore wine country.",
  },
  {
    name: "Las Positas Golf Course",
    city: "Livermore",
    region: "East Bay",
    holes: 18,
    par: 72,
    yardage: 6725,
    latitude: 37.676,
    longitude: -121.754,
    phone_number: "(925) 455-7820",
    golfnow_id: "553",
    booking_url: "https://www.golfnow.com/tee-times/facility/553-las-positas-golf-course/search",
    booking_system: "golfnow",
    description: "Well-designed course in the Livermore Valley.",
  },
  {
    name: "Pleasanton Golf Center",
    city: "Pleasanton",
    region: "East Bay",
    holes: 9,
    par: 29,
    yardage: 1345,
    latitude: 37.682,
    longitude: -121.874,
    phone_number: "(925) 462-4653",
    golfnow_id: "591",
    booking_url: "https://www.golfnow.com/tee-times/facility/591-pleasanton-golf-center/search",
    booking_system: "golfnow",
    description: "Par-3 course with practice facilities.",
  },
  {
    name: "Willow Park Golf Course",
    city: "Castro Valley",
    region: "East Bay",
    holes: 18,
    par: 71,
    yardage: 5782,
    latitude: 37.695,
    longitude: -122.081,
    phone_number: "(510) 537-8989",
    golfnow_id: "659",
    booking_url: "https://www.golfnow.com/tee-times/facility/659-willow-park-golf-course/search",
    booking_system: "golfnow",
    description: "Friendly neighborhood course in Castro Valley.",
  },
  {
    name: "Diablo Creek Golf Course",
    city: "Concord",
    region: "East Bay",
    holes: 18,
    par: 71,
    yardage: 6830,
    latitude: 37.954,
    longitude: -121.935,
    phone_number: "(925) 686-6262",
    golfnow_id: null,
    booking_url: "https://www.diablocreekgc.com/",
    booking_system: "cpsgolf",
    description: "Championship course in Concord with water hazards.",
  },
  {
    name: "Canyon Lakes Golf Course",
    city: "San Ramon",
    region: "East Bay",
    holes: 18,
    par: 71,
    yardage: 6408,
    latitude: 37.752,
    longitude: -121.938,
    phone_number: "(925) 735-6511",
    golfnow_id: null,
    booking_url: "https://www.chronogolf.com/club/canyon-lakes-golf-course-and-brewery",
    booking_system: "chronogolf",
    description: "Golf course with on-site brewery - best of both worlds!",
  },
  {
    name: "Callippe Preserve Golf Course",
    city: "Pleasanton",
    region: "East Bay",
    holes: 18,
    par: 72,
    yardage: 6767,
    latitude: 37.6247,
    longitude: -121.8532,
    phone_number: "(925) 426-6666",
    golfnow_id: "5023",
    booking_url: "https://www.golfnow.com/tee-times/facility/5023-callippe-preserve-golf-course/search",
    booking_system: "golfnow",
    description: "Beautiful preserve setting with wildlife habitat areas.",
  },
  {
    name: "Wente Vineyards",
    city: "Livermore",
    region: "East Bay",
    holes: 18,
    par: 72,
    yardage: 7012,
    latitude: 37.6247,
    longitude: -121.7232,
    phone_number: "(925) 456-2475",
    golfnow_id: "432",
    booking_url: "https://www.golfnow.com/tee-times/facility/432-the-course-at-wente-vineyards/search",
    booking_system: "golfnow",
    description: "Greg Norman design in the heart of wine country.",
  },
  {
    name: "San Ramon Golf Club",
    city: "San Ramon",
    region: "East Bay",
    holes: 18,
    par: 71,
    yardage: 6376,
    latitude: 37.7547,
    longitude: -121.9532,
    phone_number: "(925) 828-6100",
    golfnow_id: "241",
    booking_url: "https://www.golfnow.com/tee-times/facility/241-san-ramon-golf-club/search",
    booking_system: "golfnow",
    description: "Well-maintained public course in San Ramon.",
  },
  {
    name: "The Bridges Golf Club",
    city: "San Ramon",
    region: "East Bay",
    holes: 18,
    par: 72,
    yardage: 7104,
    latitude: 37.7347,
    longitude: -121.9232,
    phone_number: "(925) 735-4253",
    golfnow_id: "5141",
    booking_url: "https://www.golfnow.com/tee-times/facility/5141-the-bridges-golf-club/search",
    booking_system: "golfnow",
    description: "Upscale Johnny Miller design with excellent conditions.",
  },

  // North Bay - Marin County
  {
    name: "Peacock Gap Golf Club",
    city: "San Rafael",
    region: "North Bay",
    holes: 18,
    par: 71,
    yardage: 6253,
    latitude: 37.9856,
    longitude: -122.478,
    phone_number: "(415) 453-4940",
    golfnow_id: "588",
    booking_url: "https://www.golfnow.com/tee-times/facility/588-peacock-gap-golf-club/search",
    booking_system: "golfnow",
    description: "Well-maintained course with bay views in Marin County.",
  },
  {
    name: "Indian Valley Golf Club",
    city: "Novato",
    region: "North Bay",
    holes: 18,
    par: 72,
    yardage: 6442,
    latitude: 38.0675,
    longitude: -122.567,
    phone_number: "(415) 897-1118",
    golfnow_id: null,
    booking_url: "https://www.indianvalleygc.com",
    booking_system: "phone",
    description: "Scenic course in the hills of Novato.",
  },
  {
    name: "StoneTree Golf Club",
    city: "Novato",
    region: "North Bay",
    holes: 18,
    par: 72,
    yardage: 6890,
    latitude: 38.098,
    longitude: -122.545,
    phone_number: "(415) 209-6090",
    golfnow_id: "633",
    booking_url: "https://www.golfnow.com/tee-times/facility/633-stonetree-golf-club/search",
    booking_system: "golfnow",
    description: "Championship course with challenging elevation changes.",
  },
  {
    name: "McInnis Park Golf Center",
    city: "San Rafael",
    region: "North Bay",
    holes: 9,
    par: 31,
    yardage: 2130,
    latitude: 38.014,
    longitude: -122.532,
    phone_number: "(415) 492-1800",
    golfnow_id: null,
    booking_url: "https://www.mcinnisparkgolf.com",
    booking_system: "phone",
    description: "9-hole course with driving range and practice facilities.",
  },
  {
    name: "Mill Valley Golf Course",
    city: "Mill Valley",
    region: "North Bay",
    holes: 9,
    par: 29,
    yardage: 1620,
    latitude: 37.906,
    longitude: -122.528,
    phone_number: "(415) 388-9982",
    golfnow_id: "572",
    booking_url: "https://www.golfnow.com/tee-times/facility/572-mill-valley-golf-course/search",
    booking_system: "golfnow",
    description: "Charming 9-hole course in Mill Valley.",
  },
  {
    name: "The Links at Bodega Harbour",
    city: "Bodega Bay",
    region: "North Bay",
    holes: 18,
    par: 70,
    yardage: 6275,
    latitude: 38.334,
    longitude: -123.047,
    phone_number: "(707) 875-3538",
    golfnow_id: "149",
    booking_url: "https://www.golfnow.com/tee-times/facility/149-the-links-at-bodega-harbour/search",
    booking_system: "golfnow",
    description: "Scottish links-style course along the Sonoma Coast.",
  },
  {
    name: "Northwood Golf Club",
    city: "Monte Rio",
    region: "North Bay",
    holes: 9,
    par: 36,
    yardage: 2893,
    latitude: 38.468,
    longitude: -123.014,
    phone_number: "(707) 865-1116",
    golfnow_id: null,
    booking_url: "https://www.northwoodgolf.com/bookteetimes",
    booking_system: "cpsgolf",
    description: "Historic Alister MacKenzie design among the redwoods.",
  },
  {
    name: "Hiddenbrooke Golf Club",
    city: "Vallejo",
    region: "North Bay",
    holes: 18,
    par: 72,
    yardage: 6815,
    latitude: 38.1447,
    longitude: -122.1932,
    phone_number: "(707) 558-1140",
    golfnow_id: "527",
    booking_url: "https://www.golfnow.com/tee-times/facility/527-hiddenbrooke-golf-club/search",
    booking_system: "golfnow",
    description: "Arnold Palmer design with challenging wind conditions.",
  },
  {
    name: "Blue Rock Springs Golf Club (East)",
    city: "Vallejo",
    region: "North Bay",
    holes: 18,
    par: 72,
    yardage: 6275,
    latitude: 38.1284,
    longitude: -122.2256,
    phone_number: "(707) 643-8476",
    golfnow_id: null,
    booking_url: "https://www.chronogolf.com/club/blue-rock-springs-golf-club",
    booking_system: "chronogolf",
    description: "Municipal course with two 18-hole layouts.",
  },
  {
    name: "Mare Island Golf Club",
    city: "Vallejo",
    region: "North Bay",
    holes: 18,
    par: 70,
    yardage: 6043,
    latitude: 38.0847,
    longitude: -122.2632,
    phone_number: "(707) 562-4653",
    golfnow_id: "563",
    booking_url: "https://www.golfnow.com/tee-times/facility/563-mare-island-golf-club/search",
    booking_system: "golfnow",
    description: "Historic course on former Mare Island Naval Shipyard.",
  },
  {
    name: "Rooster Run Golf Club",
    city: "Petaluma",
    region: "North Bay",
    holes: 18,
    par: 72,
    yardage: 7001,
    latitude: 38.2747,
    longitude: -122.6432,
    phone_number: "(707) 778-1211",
    golfnow_id: "606",
    booking_url: "https://www.golfnow.com/tee-times/facility/606-rooster-run-golf-club/search",
    booking_system: "golfnow",
    description: "Award-winning course with excellent playing conditions.",
  },
  {
    name: "Adobe Creek Golf Course",
    city: "Petaluma",
    region: "North Bay",
    holes: 18,
    par: 72,
    yardage: 6302,
    latitude: 38.2547,
    longitude: -122.6232,
    phone_number: "(707) 765-3000",
    golfnow_id: "434",
    booking_url: "https://www.golfnow.com/tee-times/facility/434-adobe-creek-golf-club/search",
    booking_system: "golfnow",
    description: "Robert Trent Jones Jr. design in Petaluma.",
  },
  {
    name: "Valley of the Moon Club",
    city: "Santa Rosa",
    region: "North Bay",
    holes: 18,
    par: 72,
    yardage: 6359,
    latitude: 38.4126,
    longitude: -122.5449,
    phone_number: "(707) 539-0415",
    golfnow_id: "243",
    booking_url: "https://www.golfnow.com/tee-times/facility/243/search",
    booking_system: "golfnow",
    description: "Classic course in the Valley of the Moon.",
  },

  // Napa Valley
  {
    name: "Silverado Resort - North Course",
    city: "Napa",
    region: "Napa",
    holes: 18,
    par: 72,
    yardage: 6896,
    latitude: 38.3047,
    longitude: -122.2632,
    phone_number: "(707) 257-5460",
    golfnow_id: null,
    booking_url: "https://www.silveradoresort.com/napa-valley-golf",
    booking_system: "other",
    description: "PGA Tour venue with stunning Napa Valley views.",
  },
  {
    name: "Silverado Resort - South Course",
    city: "Napa",
    region: "Napa",
    holes: 18,
    par: 72,
    yardage: 6632,
    latitude: 38.3037,
    longitude: -122.2622,
    phone_number: "(707) 257-5460",
    golfnow_id: null,
    booking_url: "https://www.silveradoresort.com/napa-valley-golf",
    booking_system: "other",
    description: "Beautiful resort course through oak-studded hills.",
  },
  {
    name: "Napa Golf Course at Kennedy Park",
    city: "Napa",
    region: "Napa",
    holes: 18,
    par: 72,
    yardage: 6738,
    latitude: 38.2847,
    longitude: -122.2732,
    phone_number: "(707) 255-4333",
    golfnow_id: "129",
    booking_url: "https://www.golfnow.com/tee-times/facility/129-napa-golf-course/search",
    booking_system: "golfnow",
    description: "Affordable municipal option in wine country.",
  },
  {
    name: "Vintner's Golf Club",
    city: "Yountville",
    region: "Napa",
    holes: 9,
    par: 34,
    yardage: 2645,
    latitude: 38.4147,
    longitude: -122.3532,
    phone_number: "(707) 944-1992",
    golfnow_id: "1676",
    booking_url: "https://www.golfnow.com/tee-times/facility/1676-vintners-golf-club/search",
    booking_system: "golfnow",
    description: "Charming 9-hole course surrounded by vineyards.",
  },
  {
    name: "Eagle Vines Golf Club",
    city: "American Canyon",
    region: "Napa",
    holes: 18,
    par: 72,
    yardage: 7283,
    latitude: 38.1747,
    longitude: -122.2332,
    phone_number: "(707) 257-4470",
    golfnow_id: "10706",
    booking_url: "https://www.golfnow.com/tee-times/facility/10706-eagle-vines-golf-club/search",
    booking_system: "golfnow",
    description: "Championship course at the gateway to Napa Valley.",
  },
  {
    name: "Chardonnay Golf Club",
    city: "American Canyon",
    region: "Napa",
    holes: 18,
    par: 72,
    yardage: 6816,
    latitude: 38.1747,
    longitude: -122.2332,
    phone_number: "(707) 257-8950",
    golfnow_id: "463",
    booking_url: "https://www.golfnow.com/tee-times/facility/463-chardonnay-golf-club/search",
    booking_system: "golfnow",
    description: "Wine country course with vineyard views.",
  },

  // Sonoma County
  {
    name: "Bennett Valley Golf Course",
    city: "Santa Rosa",
    region: "Sonoma",
    holes: 18,
    par: 72,
    yardage: 6583,
    latitude: 38.4226,
    longitude: -122.6595,
    phone_number: "(707) 528-3673",
    golfnow_id: "8367",
    booking_url: "https://www.golfnow.com/tee-times/facility/8367-bennett-valley-golf-course/search",
    booking_system: "golfnow",
    description: "Municipal course with well-maintained greens.",
  },
  {
    name: "Windsor Golf Club",
    city: "Windsor",
    region: "Sonoma",
    holes: 18,
    par: 72,
    yardage: 6650,
    latitude: 38.5285,
    longitude: -122.8069,
    phone_number: "(707) 838-7888",
    golfnow_id: null,
    booking_url: "https://www.windsorgolf.com",
    booking_system: "phone",
    description: "Popular course in Sonoma wine country.",
  },
  {
    name: "Sonoma Golf Club",
    city: "Sonoma",
    region: "Sonoma",
    holes: 18,
    par: 72,
    yardage: 7087,
    latitude: 38.2919,
    longitude: -122.458,
    phone_number: "(707) 996-0300",
    golfnow_id: "18188",
    booking_url: "https://www.golfnow.com/tee-times/facility/18188-sonoma-golf-club/search",
    booking_system: "golfnow",
    description: "Historic course in the heart of Sonoma.",
  },
  {
    name: "Fairgrounds Golf Course",
    city: "Santa Rosa",
    region: "Sonoma",
    holes: 9,
    par: 29,
    yardage: 1800,
    latitude: 38.435,
    longitude: -122.725,
    phone_number: "(707) 577-0755",
    golfnow_id: null,
    booking_url: "https://www.fairgroundsgolf.com",
    booking_system: "phone",
    description: "Affordable 9-hole option in Santa Rosa.",
  },
  {
    name: "Oakmont Golf Club",
    city: "Santa Rosa",
    region: "Sonoma",
    holes: 18,
    par: 63,
    yardage: 4200,
    latitude: 38.445,
    longitude: -122.548,
    phone_number: "(707) 539-0415",
    golfnow_id: "8429",
    booking_url: "https://www.golfnow.com/tee-times/facility/8429-the-club-at-sugarloaf/search",
    booking_system: "golfnow",
    description: "Executive course in the Oakmont community.",
  },

  // Monterey Peninsula
  {
    name: "Pacific Grove Golf Links",
    city: "Pacific Grove",
    region: "Monterey",
    holes: 18,
    par: 70,
    yardage: 5732,
    latitude: 36.6358,
    longitude: -121.9289,
    phone_number: "(831) 648-5775",
    golfnow_id: "4739",
    booking_url: "https://www.golfnow.com/tee-times/facility/4739/search",
    booking_system: "golfnow",
    description: "Affordable seaside golf with ocean views on every hole.",
  },
  {
    name: "Bayonet Golf Course",
    city: "Seaside",
    region: "Monterey",
    holes: 18,
    par: 72,
    yardage: 7104,
    latitude: 36.618,
    longitude: -121.835,
    phone_number: "(831) 899-7271",
    golfnow_id: "25",
    booking_url: "https://www.golfnow.com/tee-times/facility/25-bayonet-golf-course/search",
    booking_system: "golfnow",
    description: "Former military course with challenging layout.",
  },
  {
    name: "Black Horse Golf Club",
    city: "Seaside",
    region: "Monterey",
    holes: 18,
    par: 72,
    yardage: 7024,
    latitude: 36.615,
    longitude: -121.832,
    phone_number: "(831) 899-7271",
    golfnow_id: "11986",
    booking_url: "https://www.golfnow.com/tee-times/facility/11986-black-horse-golf-course/search",
    booking_system: "golfnow",
    description: "Sister course to Bayonet with bay views.",
  },
  {
    name: "Del Monte Golf Course",
    city: "Monterey",
    region: "Monterey",
    holes: 18,
    par: 72,
    yardage: 6365,
    latitude: 36.595,
    longitude: -121.878,
    phone_number: "(831) 373-2700",
    golfnow_id: "13082",
    booking_url: "https://www.golfnow.com/tee-times/facility/13082-del-monte-golf-course/search",
    booking_system: "golfnow",
    description: "Oldest continuously operating course west of the Mississippi.",
  },
  {
    name: "Laguna Seca Golf Ranch",
    city: "Monterey",
    region: "Monterey",
    holes: 18,
    par: 71,
    yardage: 6174,
    latitude: 36.5847,
    longitude: -121.7631,
    phone_number: "(831) 373-3701",
    golfnow_id: "127",
    booking_url: "https://www.golfnow.com/tee-times/facility/127/search",
    booking_system: "golfnow",
    description: "Robert Trent Jones Sr. design near Laguna Seca Raceway.",
  },
  {
    name: "The Quail Golf Club",
    city: "Carmel",
    region: "Monterey",
    holes: 18,
    par: 71,
    yardage: 6500,
    latitude: 36.485,
    longitude: -121.842,
    phone_number: "(831) 620-8866",
    golfnow_id: "224",
    booking_url: "https://www.golfnow.com/tee-times/facility/224-quail-lodge-golf-club/search",
    booking_system: "golfnow",
    description: "Private club atmosphere with public access at Quail Lodge.",
  },
  {
    name: "Carmel Valley Ranch",
    city: "Carmel",
    region: "Monterey",
    holes: 18,
    par: 70,
    yardage: 6117,
    latitude: 36.478,
    longitude: -121.732,
    phone_number: "(831) 626-2510",
    golfnow_id: "107",
    booking_url: "https://www.golfnow.com/tee-times/facility/107-carmel-valley-ranch-golf-course/search",
    booking_system: "golfnow",
    description: "Pete Dye design in beautiful Carmel Valley.",
  },
  {
    name: "Corral de Tierra Country Club",
    city: "Salinas",
    region: "Monterey",
    holes: 18,
    par: 72,
    yardage: 6688,
    latitude: 36.538,
    longitude: -121.695,
    phone_number: "(831) 484-1112",
    golfnow_id: "17569",
    booking_url: "https://www.golfnow.com/tee-times/facility/17569-corral-de-tierra-country-club/search",
    booking_system: "golfnow",
    description: "Semi-private club with public tee times available.",
  },
  {
    name: "Twin Creeks Golf Course",
    city: "Salinas",
    region: "Monterey",
    holes: 9,
    par: 29,
    yardage: 1400,
    latitude: 36.678,
    longitude: -121.655,
    phone_number: "(831) 758-7333",
    golfnow_id: "17211",
    booking_url: "https://www.golfnow.com/tee-times/facility/17211-twin-creeks-golf-course/search",
    booking_system: "golfnow",
    description: "Par-3 course perfect for beginners.",
  },
  {
    name: "The Club at Crazy Horse Ranch",
    city: "Salinas",
    region: "Monterey",
    holes: 18,
    par: 72,
    yardage: 6540,
    latitude: 36.712,
    longitude: -121.598,
    phone_number: "(831) 663-2266",
    golfnow_id: "8615",
    booking_url: "https://www.golfnow.com/tee-times/facility/8615-crazy-horse-golf-club/search",
    booking_system: "golfnow",
    description: "Challenging course in the Salinas Valley.",
  },
  {
    name: "Salinas Fairways Golf Course",
    city: "Salinas",
    region: "Monterey",
    holes: 9,
    par: 28,
    yardage: 1350,
    latitude: 36.685,
    longitude: -121.638,
    phone_number: "(831) 758-7300",
    golfnow_id: "4290",
    booking_url: "https://www.golfnow.com/tee-times/facility/4290-salinas-fairways-golf-course/search",
    booking_system: "golfnow",
    description: "Affordable par-3 course in Salinas.",
  },
  {
    name: "Monterey Pines Golf Club",
    city: "Monterey",
    region: "Monterey",
    holes: 18,
    par: 69,
    yardage: 5609,
    latitude: 36.578,
    longitude: -121.852,
    phone_number: "(831) 656-2167",
    golfnow_id: "5094",
    booking_url: "https://www.golfnow.com/tee-times/facility/5094-monterey-pines-golf-club/search",
    booking_system: "golfnow",
    description: "Military course open to public with affordable rates.",
  },
]

// Add slugs to all courses
export const courses: Course[] = rawCourses.map((course) => ({
  ...course,
  slug: generateSlug(course.name),
}))

// Staff picks - featured courses
export const staffPickSlugs = [
  "tpc-harding-park",
  "pasatiempo-golf-club",
  "presidio-golf-course",
  "half-moon-bay-ocean-course",
  "corica-park-south-course",
  "cinnabar-hills-golf-club",
  "tilden-park-golf-course",
  "the-links-at-bodega-harbour",
]

export function getCourseBySlug(slug: string): Course | undefined {
  return courses.find((c) => c.slug === slug)
}

export function getCoursesByRegion(region: string): Course[] {
  return courses.filter((c) => c.region === region)
}

export function getStaffPicks(): Course[] {
  return courses.filter((c) => staffPickSlugs.includes(c.slug))
}

export function getAllRegions(): string[] {
  return [...new Set(courses.map((c) => c.region))]
}
